title: База знаний
description: База знаний компании ООО "Гарда"
syntax: XML
supportedLanguages: []
properties:
  - id: CDhLD
    name: Автор
    type: Enum
    options:
      docportalVisible: true
    icon: book-check
    values:
      - Родионов А.
      - Балицкий И.
      - Аксенова М.
      - Вакс Р.
      - Луцко Д.
