title: База знаний
description: База знаний компании ООО "Гарда"
syntax: XML
supportedLanguages: []
properties:
  - id: bUuZu
    name: fdgdfgfdg
    type: Flag
    style: blue-purple
  - id: AvZ82
    name: zzzzzzz
    type: Flag
    style: dark-orange
